name: Cache Trivy/Grype Vulnerability DB

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  cache_vuln_db:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare cache directory
        run: |
          sudo mkdir -p .trivyqq
          sudo chown -R $USER:$USER .trivy
      - name: Cache vulnerability database
        id: cache
        uses: actions/cache@v4
        with:
          path: .trivy 
          key: trivy-db-cache-${{ github.run_id }}

      - name: Download vulnerability DB
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker://ghcr.io/aquasecurity/trivy:0.37.2
        with:
          entrypoint: trivy
          args: image --download-db-only --cache-dir .trivy --debug 