name: Cache Trivy/Grype Vulnerability DB

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Trivy Cache
      uses: yogeshlonkar/trivy-cache-action@v0
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: busybox:latest
        exit-code: '1'
        ignore-unfixed: true
        cache-dir: .trivy
        