name: Cache Trivy/Grype Vulnerability DB

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  cache_vuln_db:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare cache directory
        run: |
         sudo mkdir -p /github/home/.cache/trivy;
         sudo chown -R $USER:$USER /github/home/.cache/trivy
        

      - name: Cache vulnerability database
        uses: actions/cache@v3
        with:
          path: /github/home/.cache/trivy  # Path to store the Trivy DB
          key: trivy-db-cache_${{ github.run_id }}

      - name: Download vulnerability DB
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker://ghcr.io/aquasecurity/trivy:0.37.2
        with:
          entrypoint: trivy
          args: image --download-db-only --debug 

      - name: Verify cache contents
        run: ls -la /github/home/.cache/trivy  # Check if DB is downloaded