name: Cache Trivy/Grype Vulnerability DB

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  cache_vuln_db:
    runs-on: ubuntu-latest
    steps:
      - name: Cache vulnerability database
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy/db  # Where the DB will be stored
          key: trivy-db-cache-${{ steps.get-date.outputs.date }}

      - name: Download vulnerability DB
        if: steps.cache-key.outputs.cache-hit != 'true'
        uses: docker://ghcr.io/aquasecurity/trivy:0.37.2
        with:
          entrypoint: trivy
          args: image --download-db-only --debug
